import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./containers/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "bs-blue": "#5a8dee",
        "bs-indigo": "#6610f2",
        "bs-purple": "#6f42c1",
        "bs-pink": "#e83e8c",
        "bs-red": "#ff5b5c",
        "bs-orange": "#fd7e14",
        "bs-yellow": "#fdac41",
        "bs-green": "#39da8a",
        "bs-teal": "#20c997",
        "bs-cyan": "#00cfdd",
        "bs-black": "#263c55",
        "bs-white": "#fff",
        "bs-gray": "rgba(38, 60, 85, 0.6)",
        "bs-gray-dark": "rgba(38, 60, 85, 0.8)",
        "bs-gray-25": "rgba(38, 60, 85, 0.025)",
        "bs-gray-50": "rgba(38, 60, 85, 0.06)",
        "bs-primary": "#5a8dee",
        "bs-secondary": "#69809a",
        "bs-success": "#39da8a",
        "bs-info": "#00cfdd",
        "bs-warning": "#fdac41",
        "bs-danger": "#ff5b5c",
        "bs-light": "#e5e9ed",
        "bs-dark": "#495563",
        "bs-primary-bg-subtle": "#dee8fc",
        "bs-secondary-bg-subtle": "#e1e6eb",
        "bs-success-bg-subtle": "#d7f8e8",
        "bs-info-bg-subtle": "#ccf5f8",
        "bs-warning-bg-subtle": "#ffeed9",
        "bs-danger-bg-subtle": "#ffdede",
        "bs-light-bg-subtle": "rgba(244, 245, 247, 0.55)",
        "bs-dark-bg-subtle": "rgba(38, 60, 85, 0.4)",
        "bs-primary-border-subtle": "#bdd1f8",
        "bs-secondary-border-subtle": "#c3ccd7",
        "bs-success-border-subtle": "#b0f0d0",
        "bs-info-border-subtle": "#99ecf1",
        "bs-warning-border-subtle": "#fedeb3",
        "bs-danger-border-subtle": "#ffbdbe",
        "bs-light-border-subtle": "rgba(38, 60, 85, 0.2)",
        "bs-dark-border-subtle": "rgba(38, 60, 85, 0.5)",
        "bs-primary-text-emphasis": "#24385f",
        "bs-secondary-text-emphasis": "#2a333e",
        "bs-success-text-emphasis": "#175737",
        "bs-info-text-emphasis": "#005358",
        "bs-warning-text-emphasis": "#65451a",
        "bs-danger-text-emphasis": "#662425",
        "bs-light-text-emphasis": "rgba(38, 60, 85, 0.7)",
        "bs-dark-text-emphasis": "rgba(38, 60, 85, 0.7)",
        "bs-emphasis-color": "#263c55",
        "bs-secondary-color": "rgba(103, 119, 136, 0.75)",
        "bs-tertiary-color": "rgba(103, 119, 136, 0.5)",
        "bs-highlight-color": "#677788",
        "bs-heading-color": "#516377",
        "bs-link-color": "#5a8dee",
        "bs-link-hover-color": "#517fd6",
        "bs-border-color": "#d4d8dd",
        "bs-border-color-translucent": "rgba(38, 60, 85, 0.175)",
        "bs-body-bg": "#f2f2f6",
      },
      fontFamily: {
        vazirmatn: [
          "Vazirmatn",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
      },
      // gradientColorStops: {
      //   "bs-gradient": [
      //     "rgba(255, 255, 255, 0.15)",
      //     "rgba(255, 255, 255, 0)",
      //   ],
      // },
    },
  },
  plugins: [],
} satisfies Config;
